python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_050.h5 --trials 1 --steps 40 --eps 10.0 --norm l1 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_050.h5 --trials 1 --steps 40 --eps 0.0 --norm l1 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_050.h5 --trials 1 --steps 40 --eps 1.0 --norm l2 --gpu 1  | tee -a fmnist_training_output.csv &
wait
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_050.h5 --trials 1 --steps 40 --eps 0.0 --norm l2 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_050.h5 --trials 1 --steps 40 --eps 0.1 --norm linf --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_050.h5 --trials 1 --steps 40 --eps 0.0 --norm linf --gpu 1  | tee -a fmnist_training_output.csv &
wait
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_042.h5 --trials 1 --steps 40 --eps 10.0 --norm l1 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_042.h5 --trials 1 --steps 40 --eps 0.0 --norm l1 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_042.h5 --trials 1 --steps 40 --eps 1.0 --norm l2 --gpu 1  | tee -a fmnist_training_output.csv &
wait
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_042.h5 --trials 1 --steps 40 --eps 0.0 --norm l2 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_042.h5 --trials 1 --steps 40 --eps 0.1 --norm linf --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_042.h5 --trials 1 --steps 40 --eps 0.0 --norm linf --gpu 1  | tee -a fmnist_training_output.csv &
wait
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_036.h5 --trials 1 --steps 40 --eps 10.0 --norm l1 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_036.h5 --trials 1 --steps 40 --eps 0.0 --norm l1 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_036.h5 --trials 1 --steps 40 --eps 1.0 --norm l2 --gpu 1  | tee -a fmnist_training_output.csv &
wait
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_036.h5 --trials 1 --steps 40 --eps 0.0 --norm l2 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_036.h5 --trials 1 --steps 40 --eps 0.1 --norm linf --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_65_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_0_036.h5 --trials 1 --steps 40 --eps 0.0 --norm linf --gpu 1  | tee -a fmnist_training_output.csv &
wait
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_025.h5 --trials 1 --steps 40 --eps 10.0 --norm l1 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_025.h5 --trials 1 --steps 40 --eps 0.0 --norm l1 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_025.h5 --trials 1 --steps 40 --eps 1.0 --norm l2 --gpu 1  | tee -a fmnist_training_output.csv &
wait
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_025.h5 --trials 1 --steps 40 --eps 0.0 --norm l2 --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_025.h5 --trials 1 --steps 40 --eps 0.1 --norm linf --gpu 1  | tee -a fmnist_training_output.csv &
python main.py --dataset FMNIST --attack pgd --fname ../../training/mnist/FMNIST/MLP_model_comps_4_dataset_FMNIST_method_svd_v2_0_freezed_1_denses_1_dense-size_256_recon_0_regularizer_1_025.h5 --trials 1 --steps 40 --eps 0.0 --norm linf --gpu 1  | tee -a fmnist_training_output.csv &
wait
