python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 3 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 128 --gpu 2 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 1 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 0 --dense_size 256 --gpu 3 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 2 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 128 --gpu 1 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 3 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 1 --dense_size 256 --gpu 2 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 1 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 128 --gpu 3 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 2 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 2 --dense_size 256 --gpu 1 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 3 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 128 --gpu 2 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 1 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 3 --dense_size 256 --gpu 3 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 2 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 128 --gpu 1 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 16 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 23 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 34 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 3 &
wait
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 53 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 103 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 281 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 0 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 3 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 1 --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 1 &
python train.py --save_dir MNIST --dataset MNIST --epoch 100 --comps 458 --method svd  --reconstruct 2  --freeze 1 --normalize1 0 --normalize2 0 --denses 4 --dense_size 256 --gpu 2 &
wait
